# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/theme-documentation-basics/#site-configuration
# -------------------------------------------------------------------------------------

# FixIt 0.2.15 | CHANGED FixIt theme version
version = "0.3.X" # e.g. "0.2.X", "0.2.15", "v0.2.15" etc.
# site description
description = "七彩直播视频创研社成人福利导,你的性福指南，及时收录宅男福利网址，让您更便捷快速地获得性福体验！"
#description = "6D直播 成人 视频 直播"
# site keywords
keywords = ["七彩导航,七彩福利导航,七彩色情导航,七彩黄色导航"]
# site default theme ["light", "dark", "auto"]
defaultTheme = "auto"
# which hash function used for SRI, when empty, no SRI is used
# ["sha256", "sha384", "sha512", "md5"]
fingerprint = ""
# NEW date format
dateFormat = "2006-01-02"
# website images for Open Graph and Twitter Cards
images = []
# FixIt 0.2.12 | NEW enable PWA
enablePWA = true
# FixIt 0.2.14 | NEW whether to add external Icon for external links automatically
externalIcon = false
# FixIt 0.3.0 | NEW whether to reverse the order of the navigation menu
navigationReverse = false
# FixIt 0.3.0 | NEW whether to add site title to the title of every page
# remember to set up your site title in `hugo.toml` (e.g. title = "title")
withSiteTitle = true
# FixIt 0.3.0 | NEW title delimiter when the site title is be added to the title of every page
titleDelimiter = "-"
# FixIt 0.3.0 | NEW whether to add site subtitle to the title of index page
# remember to set up your site subtitle by `params.header.subtitle.name`
indexWithSubtitle = false
# FixIt 0.2.14 | NEW FixIt will, by default, inject a theme meta tag in the HTML head on the home page only.
# You can turn it off, but we would really appreciate if you don’t, as this is a good way to watch FixIt's popularity on the rise.
disableThemeInject = false

# Author Configuration
[author]
  name = ""
  email = ""
  link = ""
  avatar = ""

# FixIt 0.3.0 | NEW public Git repository information only then enableGitInfo is true
# App icon config
[app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  title = "直播视频创研社"
  # whether to omit favicon resource links
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  svgFavicon = "/images/logo-6d.png"
  # Safari mask icon color
  iconColor = "#5bbad5"
  # Windows v8-10 tile color
  tileColor = "#da532c"
  # FixIt 0.2.12 | CHANGED Android browser theme color
  [app.themeColor]
    light = "#f8f8f8"
    dark = "#252627"


# Header config
[header]
  # FixIt 0.2.13 | CHANGED desktop header mode ["sticky", "normal", "auto"]
  desktopMode = "sticky"
  # FixIt 0.2.13 | CHANGED mobile header mode ["sticky", "normal", "auto"]
  mobileMode = "auto"
  # Header title config
  [header.title]
    # URL of the LOGO
    logo = ""
    # title name
    name = "直播视频创研社"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # whether to use typeit animation for title name
    typeit = false
  # FixIt 0.2.12 | NEW Header subtitle config
  [header.subtitle]
    # subtitle name
    name = ""
    # whether to use typeit animation for subtitle name
    typeit = false


# Footer config
[footer]
  enable = true
  # whether to show copyright info
  copyright = true
  # whether to show the author
  author = false
  # Site creation year
  since = 2025
  # FixIt 0.2.12 | NEW Public network security only in China (HTML format is supported)
  gov = ""
  # ICP info only in China (HTML format is supported)
  icp = ""
  # license info (HTML format is supported)
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
  # FixIt 0.3.0 | NEW whether to show Hugo and theme info
  [footer.powered]
    enable = true
    hugoLogo = true
    themeLogo = true
  # FixIt 0.2.17 | CHANGED Site creation time
  [footer.siteTime]
    enable = true
    animate = true
    icon = "fa-solid fa-heartbeat"
    pre = ""
    value = "2022-07-22T24:00:00+08:00" # e.g. "2021-12-18T16:15:22+08:00"
  # FixIt 0.2.17 | NEW footer lines order, optional values: ["first", 0, 1, 2, 3, 4, 5, "last"]
  [footer.order]
    powered = 0
    copyright = 0
    statistics = 0
    visitor = 0
    beian = 0

# FixIt 0.3.0 | NEW Archives page config (all pages of posts type)
[archives]
  # special amount of posts in archives page
  paginate = 20
  # date format (month and day)
  dateFormat = "2006-01-02"

# Section page config (all pages in section)
[section]
  # special amount of pages in each section page
  paginate = 20
  # date format (month and day)
  dateFormat = "2006-01-02"
  # FixIt 0.3.10 | NEW Section feed config for RSS, Atom and JSON feed.
  [section.feed]
    # The number of posts to include in the feed. Default is -1, which means all posts.
    limit = -1
    # whether to show the full text content in feed.
    fullText = false
  # FixIt 0.2.13 | NEW recently updated pages config
  # TODO refactor to support archives, section, taxonomy and term
  [section.recentlyUpdated]
    enable = false
    rss = false
    days = 30
    maxCount = 10

# List (category or tag) page config
[list]
  # special amount of posts in each list page
  paginate = 20
  # date format (month and day)
  dateFormat = "2006-01-02"
  # FixIt 0.3.10 | NEW Term list feed config for RSS, Atom and JSON feed.
  [list.feed]
    # The number of posts to include in the feed. Default is -1, which means all posts.
    limit = -1
    # whether to show the full text content in feed.
    fullText = false


# Home page config
[home]
  # Home page profile
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/logo-6d.png"
    # FixIt 0.2.17 | NEW identifier of avatar menu link
    avatarMenu = ""
    # title shown in home page (HTML format is supported)
    title = "直播视频创研社"
    # subtitle shown in home page
    subtitle = "成年人的专属空间，实时互动尽享精彩!"
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 4

# FixIt 0.2.16 | CHANGED Social config about the author
[social]
  GitHub = "aldult-live/aldult-live.github.io"
  Linkedin = ""
  Twitter = "wegame33"
  Instagram = ""
  Facebook = ""
  Telegram = ""
  Medium = ""
  Gitlab = "seo8235612/seo"
  Youtubelegacy = ""
  Youtubecustom = ""
  Youtubechannel = "UCUbLD20SLy54FB7vnF1ellA"
  Tumblr = ""
  Quora = ""
  Keybase = ""
  Pinterest = ""
  Reddit = ""
  Codepen = ""
  FreeCodeCamp = ""
  Bitbucket = ""
  Stackoverflow = ""
  Weibo = ""
  Odnoklassniki = ""
  VK = ""
  Flickr = ""
  Xing = ""
  Snapchat = ""
  Soundcloud = ""
  Spotify = ""
  Bandcamp = ""
  Paypal = ""
  Fivehundredpx = ""
  Mix = ""
  Goodreads = ""
  Lastfm = ""
  Foursquare = ""
  Hackernews = ""
  Kickstarter = ""
  Patreon = ""
  Steam = ""
  Twitch = ""
  Strava = ""
  Skype = ""
  Whatsapp = ""
  Zhihu = ""
  Douban = ""
  Angellist = ""
  Slidershare = ""
  Jsfiddle = ""
  Deviantart = ""
  Behance = ""
  Dribbble = ""
  Wordpress = ""
  Vine = ""
  Googlescholar = ""
  Researchgate = ""
  Mastodon = ""
  Thingiverse = ""
  Devto = ""
  Gitea = ""
  XMPP = ""
  Matrix = ""
  Bilibili = ""
  ORCID = ""
  Liberapay = ""
  Ko-Fi = ""
  BuyMeaCoffee = ""
  Linktree = ""
  QQ = ""
  QQGroup = "" # https://qun.qq.com/join.html
  Diaspora = ""
  CSDN = ""
  Discord = ""
  DiscordInvite = ""
  Lichess = ""
  Pleroma = ""
  Kaggle = ""
  MediaWiki= ""
  Plume = ""
  HackTheBox = ""
  RootMe = ""
  Feishu = ""
  TryHackMe = ""
  Douyin = ""
  TikTok = ""
  Phone = ""
  Email = ""
  RSS = true

# TypeIt config
[typeit]
  # typing speed between each step (measured in milliseconds)
  speed = 100
  # blinking speed of the cursor (measured in milliseconds)
  cursorSpeed = 1000
  # character used for the cursor (HTML format is supported)
  cursorChar = "|"
  # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
  duration = -1
  # FixIt 0.2.18 | NEW whether your strings will continuously loop after completing
  loop = false

# FixIt 0.2.15 | NEW Mermaid config
[mermaid]
  # For values, see https://mermaid.js.org/config/theming.html#available-themes
  themes = ["default", "dark"]

# FixIt 0.2.12 | NEW PanguJS config
[pangu]
  # For Chinese writing
  enable = false
  selector = "article" # FixIt 0.2.17 | NEW


# FixIt 0.3.10 | NEW Busuanzi count
[busuanzi]
  # whether to enable busuanzi count
  enable = true
  # busuanzi count core script source. Default is https://vercount.one/js
  source = "https://vercount.one/js"
  # whether to show the site views
  siteViews = true
  # whether to show the page views
  pageViews = true

# Compatibility config
[compatibility]
  # whether to use Polyfill.io to be compatible with older browsers
  polyfill = false
  # whether to use object-fit-images to be compatible with older browsers
  objectFit = false

# FixIt 0.2.16 | NEW Back to top
[backToTop]
  enable = true
  # Scroll percent label in b2t button
  scrollpercent = true

# FixIt 0.2.16 | NEW Reading progress bar
[readingProgress]
  enable = true
  # Available values: ["left", "right"]
  start = "left"
  # Available values: ["top", "bottom"]
  position = "top"
  reversed = false
  light = ""
  dark = ""
  height = "2px"

# FixIt 0.3.10 | NEW Global Feed config for RSS, Atom and JSON feed.
[feed]
  # The number of posts to include in the feed. Default is -1, which means all posts.
  limit = 10
  # whether to show the full text content in feed.
  fullText = true

# Page config
[page]
  # FixIt 0.2.18 | NEW whether to enable the author's avatar of the post
  authorAvatar = false
  # whether to hide a page from home page
  hiddenFromHomePage = false
  # whether to hide a page from search results
  hiddenFromSearch = false
  # FixIt 0.3.0 | NEW whether to hide a page from related posts
  hiddenFromRelated = false
  # FixIt 0.3.10 | NEW whether to hide a page from RSS, Atom and JSON feed
  hiddenFromFeed = false
  # whether to enable twemoji
  twemoji = false
  # FixIt 0.2.18 | CHANGED whether to enable lightgallery
  # set to true, images in the content will be shown as the gallery if the image has a title, e.g. ![alt](src "title")
  # set to "force", images in the content will be forced to shown as the gallery regardless of the image has a title or not, e.g. ![alt](src)
  lightgallery = false
  # whether to enable the ruby extended syntax
  ruby = true
  # whether to enable the fraction extended syntax
  fraction = true
  # whether to enable the fontawesome extended syntax
  fontawesome = true
  # license info (HTML format is supported)
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
  # whether to show link to Raw Markdown content of the post
  linkToMarkdown = true
  # FixIt 0.3.0 | NEW whether to show link to view source code of the post
  linkToSource = true
  # FixIt 0.3.0 | NEW whether to show link to edit the post
  linkToEdit = true
  # FixIt 0.3.0 | NEW whether to show link to report issue for the post
  linkToReport = true
  # whether to show the full text content in RSS
  rssFullText = false
  # FixIt 0.3.10 | CHANGED Page style ["narrow", "normal", "wide", ...]
  pageStyle = "normal"
  # FixIt 0.2.17 | CHANGED Auto Bookmark Support
  # If true, save the reading progress when closing the page.
  autoBookmark = false
  # FixIt 0.2.17 | NEW whether to enable wordCount
  wordCount = true
  # FixIt 0.2.17 | NEW whether to enable readingTime
  readingTime = true
  # FixIt 0.2.17 | NEW end of post flag
  endFlag = ""
  # FixIt 0.2.18 | NEW whether to enable instant.page
  instantPage = false
  # FixIt 0.3.0 | NEW whether to enable collection list at the sidebar
  collectionList = false
  # FixIt 0.3.0 | NEW whether to enable collection navigation at the end of the post
  collectionNavigation = false

  # FixIt 0.2.15 | NEW Repost config
  [page.repost]
    enable = false
    url = ""
  # Table of the contents config
  [page.toc]
    # whether to enable the table of the contents
    enable = true
    # whether to keep the static table of the contents in front of the post
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    auto = true
    # FixIt 0.2.13 | NEW position of TOC ["left", "right"]
    position = "right"
  # FixIt 0.2.13 | NEW Display a message at the beginning of an article to warn the reader that its content might be expired
  [page.expirationReminder]
    enable = false
    # Display the reminder if the last modified time is more than 90 days ago
    reminder = 180
    # Display warning if the last modified time is more than 180 days ago
    warning = 360
    # If the article expires, close the comment or not
    closeComment = false
  # FixIt 0.3.0 | NEW page heading config
  [page.math]
    enable = true
    # default inline delimiter is $ ... $ and \( ... \)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true
  # Code wrapper config
  [page.code]
    # FixIt 0.3.9 | NEW whether to enable the code wrapper
    enable = true
    # whether to show the copy button of the code wrapper
    copy = true
    # FixIt 0.2.13 | NEW whether to show the edit button of the code wrapper
    edit = true
    # the maximum number of lines of displayed code by default
    maxShownLines = 100
  # Mapbox GL JS config (https://docs.mapbox.com/mapbox-gl-js)
  [page.mapbox]
    # access token of Mapbox GL JS
    accessToken = ""
    # style for the light theme
    lightStyle = "mapbox://styles/mapbox/light-v9"
    # style for the dark theme
    darkStyle = "mapbox://styles/mapbox/dark-v9"
    # whether to add NavigationControl
    navigation = true
    # whether to add GeolocateControl
    geolocate = true
    # whether to add ScaleControl
    scale = true
    # whether to add FullscreenControl
    fullscreen = true
  # FixIt 0.3.0 | NEW [Experimental] cache remote images locally, see: https://github.com/hugo-fixit/FixIt/pull/362
  [page.cacheRemoteImages]
    enable = false
    # replace remote image url with local image url (place in public/images/remote/)
    replace = false
  # FixIt 0.3.0 | NEW Related content config (https://gohugo.io/content-management/related/)
  [page.related]
    enable = false
    count = 5
  # FixIt 0.2.17 | NEW Donate (Sponsor) settings
  [page.reward]
    enable = false
    animation = true
    # position relative to post footer, optional values: ["before", "after"]
    position = "after"
    comment = "文章有帮到您的话，请我喝杯奶茶吧ヾ(●´∀｀●)"
    # FixIt 0.2.18 | NEW display mode of QR code images, optional values: ["static", "fixed"], default: `static`
    mode = "static"
    [page.reward.ways]
      wechatpay = "/images/wechat.png"
      alipay = "/images/alipay.png"
      # paypal = "/images/paypal.png"
      # bitcoin = "/images/bitcoin.png"
  # social share links in post page
  [page.share]
    enable = true
    X = true
    Facebook = true
    Linkedin = false
    Whatsapp = false
    Pinterest = false
    Tumblr = false
    HackerNews = false
    Reddit = false
    VK = false
    Buffer = false
    Xing = false
    Line = false
    Instapaper = false
    Pocket = false
    Flipboard = false
    Weibo = true
    Myspace = false
    Blogger = false
    Baidu = false
    Odnoklassniki = false
    Evernote = false
    Skype = false
    Trello = false
    Mix = false
  # FixIt 0.2.15 | CHANGED Comment config
  [page.library]
    [page.library.css]
      # someCSS = "some.css"
      # located in "assets/"
      # Or
      # someCSS = "https://cdn.example.com/some.css"
    [page.library.js]
      # someJavascript = "some.js"
      # located in "assets/"
      # Or
      # someJavascript = "https://cdn.example.com/some.js"
  # Page SEO config
  [page.seo]
    # image URL
    images = []
    # Publisher info
    [page.seo.publisher]
      name = ""
      logoUrl = "/images/logo-6d.png"

# Analytics config
[analytics]
  enable = true
  # Google Analytics
  [analytics.google]
    id = "G-32T6VQ6MDN"
    # whether to anonymize IP
    anonymizeIP = true
  # Fathom Analytics
  [analytics.fathom]
    id = ""
    # server url for your tracker if you're self hosting
    server = ""
